name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Fix / Regenerate Android Project Folder
        run: |
          flutter create -t app temp_proj
          rm -rf android
          cp -r temp_proj/android android
          rm -rf temp_proj

      - name: Install dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Check APK File
        run: |
          ls -lah build/app/outputs/flutter-apk/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
          retention-days: 7

