- name: Build Release APK
  run: flutter build apk --release

- name: Check APK File
  run: |
    ls -lah build/app/outputs/flutter-apk/

- name: Upload APK Artifact
  uses: actions/upload-artifact@v4
  with:
    name: app-release-apk
    path: build/app/outputs/flutter-apk/app-release.apk
    if-no-files-found: error
    retention-days: 7