name: Build and Deploy Web

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
          cache: true

      - name: Create Web Platform Files
        run: flutter create . --platforms=web --project-name apna_khata

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Web Release
        run: flutter build web --release --base-href "/Apna-Khata-/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
